language: java

jdk:
- oraclejdk8

script:
- mvn verify

after_success:
- mvn coveralls:report
- set | grep TRAVIS
- test "${TRAVIS_PULL_REQUEST}" == "false" && test "${TRAVIS_TAG}" != "" && mvn deploy --settings conf/travis_settings.xml

deploy:
  on:
    tags: true
    skip_cleanup: true
    overwrite: true

branches:
  only:
  - master
  - /^v[0-9]+(\.[0-9]+\.[0-9]+)+/

cache:
  directories:
  - ~/.m2

env:
  global:
  - secure: hgwckZqnDFNPAPoXNYUD+kysojOl3eI8sMrWbG5q1ztDhePtdN+dTlwWhQcUMBw0Z65P7HQrRDkbKx2n8OC2wVMTyalwUn4o/xZS/ZAEpj5UycDdifTPDE/5pBH5YmXEJioZ13lr9JZdyI83EPeTj5d2flC29ToJNgJMVTPRg22x9Ss6W3IBAZsKzGM4AsHwZ1voAiUziYqnp/8SM2Gm2o/rcFZWzINFhONcJurT6eMKs4SuIPOUH/z4Zia4g9hV9NIC64rmZCbbMH1YhKcbiWb7R8ulc/YVfGuItobxdsocb/f/FUzENgYmFbkLof4IAhZxpu1EzijUqQRZfO2O0umc99xQPmqYaEVOGJ5asBJgwvDzcDULn0twvYtNeX7DadB72cJCJPjxgqdYTs/5kPZFJ9hh98J9H/5aeq0eaXkaUv4PnmFwaN1SYx0j8dn2/nNqyiXN4f6aniAH/CjJwLVCkQSLQbzExiV8RVxVvAv5UV4S6MYEdCqMcrqlZlKBvL8/4EUTQ88yoXD6kwns/FgjPInu07gYEfyiuDwFOCYCZ13U8jKfhcZc73Lx/Gc9+GajATDAN+hrN78d0QyoR032rgSa20a0lAtIr+dDX39dBhz9teoWJCJdRo6IJjQ91RF8igyBaBcbfh5BpeLO8iirmybX6Zo8Zywdcc1Tk4M=
  - secure: f5i+x4rtQBMEEGKVcVIs1wfUXy1sGHFyHJPk7BWKro1x72pLvq3zVpG2AMLJlN6mFSKTDU2Gka9jzC5wb19Wq3NoTyReHwVTquHMxKFaNTMn1DflZowbvaRt3OMY/TIZamREQ5rxWPg9gN6OkF5wS2HSb6ym8pV/hn6DfRnc+qebj5lUy8cSQmwaFHTceVm0ZjI8SiK6WNerEp8ArAVkQTacvq6CLS57INmVPShqyRVrquqv/wj0X0bl0Uit6H5/O+3ZXbTCtn3aIg0YmQAde+llH68vtznwM7cp2VU+R5g8mITo2pqQ6nMBUrBpV1u8Pa0rrw0JEHlnPMd0bzj44JswLpXl/RsmdlU5CZHk8lO6gxZRB/zmqSGfNu/oJKY0a/lp3xIA0KJZ8rWCsMVVh4yAqlZUeikM1S2jWhdt9I+VA2RtctiD2BH8pkpTKPE6S+p2/f0PF9hAzKz5nOy962DuWlYtwuLtcEWRo08idNErRluN/MjuYD0jxXG91TJZK3lOautyyA/XnX2omXwLpxX8BqjJkVati1MMyWx8azccz9ue7WojoBqZ6OXATgRJDOO9iWgjdtJ4HC+QpO4a89B+dirj7WVvy6USP081Uq54QG/S89oSqW6kYMOHeSO/ix9FzboKcn23CHtQWJGZ4uwlS812NHM0Lz3sfsnk8Cw=
